package Operators;

import java.util.Scanner;

public class Calculator {
	public static void main(String args[])
	{	
		System.out.println("Addition");
		System.out.println("  --------");
		System.out.println("enter 2 numbers:");
		Scanner S= new Scanner(System.in);
		System.out.println("number1:");
		int number1= S.nextInt();
		System.out.println("number2:");
		int number2= S.nextInt();
		int result= number1 + number2;
		System.out.println("result:"+result);
		System.out.println();
		
		System.out.println("Substraction");
		System.out.println("  -----------");
		System.out.println("enter 2 numbers:");
		Scanner S1=new Scanner(System.in);
		System.out.println("num1");
		int num1=S1.nextInt();
		System.out.println("num2");
		int num2=S1.nextInt();
		int result1=num1-num2;
		System.out.println("result:"+result1);
		System.out.println();
		
		System.out.println("Multiplication");
		System.out.println("  --------------");
		System.out.println("enter 2 numbers");
		Scanner S2=new Scanner(System.in);
		System.out.println("no1:");
		int no1= S2.nextInt();
		System.out.println("no2:");
		int no2=S2.nextInt();
		int result2=no1*no2;
		System.out.println("result:"+result2);
		System.out.println();
		
		System.out.println("Division");
		System.out.println(" -------");
		System.out.println("enter 2 numbers");
		Scanner S3=new Scanner(System.in);
		System.out.println("No1:");
		int No1= S3.nextInt();
		System.out.println("No2:");
		int No2=S3.nextInt();
		int result3=No1/No2;
		System.out.println("result:"+result3);
		System.out.println();
		
		System.out.println("Modeless");
		System.out.println("  -------");
		System.out.println("enter 2 numbers");
		Scanner S4=new Scanner(System.in);
		System.out.println("Num1:");
		int Num1= S4.nextInt();
		System.out.println("Num2:");
		int Num2=S4.nextInt();
	    int result4=Num1%Num2;
		System.out.println("result:"+result4);
		System.out.println();	
		System.out.println("<");
		Scanner S5=new Scanner(System.in);
		System.out.println("enter num1:");
		int n1= S.nextInt();
		System.out.println("enter num2:");
		int n2=S.nextInt();
		System.out.println(n1<n2);
		System.out.println();
		System.out.println(">");
		Scanner S6=new Scanner(System.in);
		System.out.println("enter num1:");
		int m1= S.nextInt();
		System.out.println("enter num2:");
		int m2=S.nextInt();
		System.out.println(m1>m2);
		System.out.println();
		System.out.println("<=");
		Scanner S7=new Scanner(System.in);
		System.out.println("enter num1:");
		int nu1= S.nextInt();
		System.out.println("enter num2:");
		int nu2=S.nextInt();
		System.out.println(nu1<=nu2);
		System.out.println();
		System.out.println(">=");
		Scanner S8=new Scanner(System.in);
		System.out.println("enter num1:");
		int M1= S.nextInt();
		System.out.println("enter num2:");
		int M2=S.nextInt();
		System.out.println(M1>=M2);
		System.out.println();
		System.out.println("==");
		Scanner S9=new Scanner(System.in);
		System.out.println("enter num1:");
		int r1= S.nextInt();
		System.out.println("enter num2:");
		int r2=S.nextInt();
		System.out.println(r1==r2);
		System.out.println();
		System.out.println("!=");
		Scanner S_1=new Scanner(System.in);
		System.out.println("enter num1:");
		int nr1= S.nextInt();
		System.out.println("enter num2:");
		int nr2=S.nextInt();
		System.out.println(nr1!=nr2);
		System.out.println();
		System.out.println("ConditionalOperations");
		Scanner S_2=new Scanner(System.in);
		System.out.println("enter num1:");
		int a= S.nextInt();
		System.out.println("enter num2:");
		int b=S.nextInt();
		System.out.println(a!=b);
		String out= a!=b?"Yes":"No";
		System.out.println(out);
		Scanner S_3=new Scanner(System.in);
		System.out.println("enter num1:");
		int c= S.nextInt();
		System.out.println("enter num2:");
		int d=S.nextInt();
		System.out.println(nr1!=nr2);
		System.out.println();
	    String out1= c>d?"Yes":"No";
		System.out.println(out1);
		System.out.println();
		System.out.println("&&");
		System.out.println("enter the boolean number");
		Scanner S_4=new Scanner(System.in);
		boolean b1=S.nextBoolean();
		boolean b2=S.nextBoolean();
		System.out.println("b1&&b2=>"+(b1&&b2));
		System.out.println();
		System.out.println("||");
		System.out.println("enter boolean:");
		Scanner S_5=new Scanner(System.in);
		boolean a1=S.nextBoolean();
		boolean a2=S.nextBoolean();
		System.out.println("a1||a2:"+(a1||a2));
		System.out.println();
		System.out.println("!");
		System.out.println("Enter the boolean:");
		Scanner S_6=new Scanner(System.in);
		boolean r=S.nextBoolean();
		System.out.println("!r:"+(!r));
		System.out.println("&");
		Scanner S_7=new Scanner(System.in);
		System.out.println("num1");
		int n3=S.nextInt();
		System.out.println("num2");
		int n4=S.nextInt();
		System.out.println(n3&n4);
		System.out.println("|");
		Scanner S_8=new Scanner(System.in);
		System.out.println("num1");
		int nm1=S.nextInt();
		System.out.println("num2");
		int nm2=S.nextInt();
		System.out.println(nm1|nm2);
		System.out.println("~");
		Scanner S_9=new Scanner(System.in);
		System.out.println("No1");
		int No=S.nextInt();
		System.out.println(~No);
		System.out.println("^");
		Scanner S11=new Scanner(System.in);
		System.out.println("Num1");
		int Nu1=S.nextInt();
		System.out.println("Num2");
		int Nu2=S.nextInt();
		System.out.println(Num1^Num2);
		System.out.println("<<");
		Scanner S12=new Scanner(System.in);
		System.out.println("Num");
		int Num=S.nextInt();
		System.out.println(Num<<1);
		
		
		

	}
}
